version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8081:8080"
    networks:
      - app-network
    volumes:
      - ./target:/app

networks:
  app-network: